/** base level units to check for */
module.exports = {
  digits: /[0-9]/,
  alpha: /[A-Za-z_]/,
  dot: /\./,
  doubleQuotes: /"/,
  plus: /\+/,
  hyphen: /\-/,
  asterisk: /\*/,
  modulo: /%/,
  forwardSlash: /\//,
  backSlash: /\\/,
  caret: /\^/,
  leftParen: /\(/,
  rightParen: /\)/,
  leftSquare: /\[/,
  rightSquare: /\]/,
  leftCurly: /\{/,
  rightCurly: /\}/,
  comma: /,/,
  ampersand: /&/,
  pipe: /\|/,
  exclamation: /!/,
  equals: /=/,
  leftArrow: /</,
  rightArrow: />/,
  lineEndings: /\n|;/,
  spacesAndTabs: /\s|\t/, // ignored
};
